---
Name: simplecalendarfilterable
Only:
  classexists: 'Restruct\SilverStripe\FilterableArchive\FilterableArchiveHolderExtension'
---

Restruct\SilverStripe\SimpleCalendar\SimpleCalendarPage:
  extensions:
    - Restruct\SilverStripe\FilterableArchive\FilterableArchiveHolderExtension
  pagination_control_tab: "Root.Filtering"
  managed_object_class: Restruct\SilverStripe\SimpleCalendar\Event
  managed_object_date_field: "Date"
  managed_object_date_sort: "ASC"
  paginate_objects: 'false'

Restruct\SilverStripe\SimpleCalendar\SimpleCalendarController:
  extensions:
    - Restruct\SilverStripe\FilterableArchive\FilterableArchiveHolderControllerExtension


Restruct\SilverStripe\SimpleCalendar\Event:
#  extensions:
#    - Restruct\SilverStripe\FilterableArchive\FilterableArchiveItemExtension
  holder_relation_fieldname: "Calendar"
  tags_active: 'false'
  #categories_fieldtype: 'TagField'
  fields_insert_before: "Date"

Restruct\SilverStripe\SimpleCalendar\ICSFeed:
#  extensions:
#    - Restruct\SilverStripe\FilterableArchive\FilterableArchiveItemExtension
  holder_relation_fieldname: "Calendar"
  tags_active: 'false'
  categories_fieldtype: 'TagField'
